/**
 * Created by taotao on 2017/5/22.
 */
(function (angular,$){
    angular.module("lo_register",["ngRoute"])
        .config(["$routeProvider",function($routeProvider){
            $routeProvider.when("/lo_register",{
                templateUrl:"lo_register/lo_register.html",
                controller:"loRegisterCtrl"
            });
        }])
        .controller("loRegisterCtrl",["$scope","$http","$window","$timeout","$location",function($scope,$http,$window,$timeout,$location){
            $scope.login=true;
            $scope.register=false;
            $scope.user="";
            $scope.password="";
            $scope.logonInfo="";
            $scope.loginAlert=false;
            $scope.reUser="";
            $scope.rePassword="";
            $scope.rePassword1="";
            $scope.registerInfo="";
            $scope.registerAlert=false;
            $scope.loading=false;
            $scope.showLogin=function(){
                $scope.login=true;
                $scope.register=false;
            };
            $scope.showRegister=function(){
                $scope.login=false;
                $scope.register=true;
            };
            $scope.hideAlert=function(){
                $scope.loginAlert=false;
                $scope.registerAlert=false;
            };
            $scope.doRegister=function(){
                if($scope.rePassword!=$scope.rePassword1){
                    $scope.registerAlert=true;
                    $scope.registerInfo="两次输入的密码不一致，请重新输入";
                    return;
                }
                if($.trim($scope.reUser)==""){
                    $scope.registerAlert=true;
                    $scope.registerInfo="用户名不能为空，请重新输入";
                    return;
                }
                $http({
                    method:"post",
                    url:"/doRegister",
                    data:{
                        user:$scope.reUser,
                        password:$scope.rePassword
                    }
                }).then(function(res){
                    if(res.data=="-1"){
                        $scope.registerAlert=true;
                        $scope.registerInfo="用户名已被占用，请更换";
                        return;
                    }
                    if(res.data=="1"){
                        $scope.loading=true;
                        $window.localStorage.login=true;
                        $window.localStorage.username=$scope.reUser;
                        $scope.reUser="";
                        $scope.rePassword="";
                        $scope.rePassword1="";
                        $timeout(function(){
                            $scope.registerAlert=false;
                            $scope.loading=false;
                            $location.path("/all_talk")
                        },2000);
                        return;
                    }
                },function(err){
                    console.log(err);
                    return;
                })
            };
        $scope.doLogin=function(){
            if($scope.user==""){
                $scope.loginAlert=true;
                $scope.loginInfo="用户名不得为空，请输入用户名";
                return;
            }
            if($scope.password==""){
                $scope.loginAlert=true;
                $scope.loginInfo="密码不得为空，请输入密码";
                return;
            }
            $http({
                url:"/doLogin",
                method:"post",
                data:{
                    username:$scope.user,
                    password:$scope.password
                }
            }).then(function(res){
                if(res.data=="-2"){
                    $scope.loginAlert=true;
                    $scope.loginInfo="用户名错误，请重新输入";
                    return;
                }
                if(res.data=="-1"){
                    $scope.loginAlert=true;
                    $scope.loginInfo="密码错误，请重新输入";
                    return;
                }
                if(res.data=="1"){
                    $scope.loading=true;
                    $window.localStorage.login=true;
                    $window.localStorage.username=$scope.user;
                    $scope.user="";
                    $scope.password="";
                    $scope.loginAlert=true;
                    $scope.loginInfo="登录成功";
                    $timeout(function(){
                        $scope.loginAlert=false;
                        $scope.loading=false;
                        $location.path("/all_talk")
                    },1000);
                    return;
                }
            },function(err){
                console.log(err);
                return;
            });
        }
        }])
})(angular,jQuery);

