/**
 * Created by taotao on 2017/5/22.
 */
(function(angular,$){
    angular.module("all_talk",["ngRoute","format_date"])
        .config(["$routeProvider",function($routeProvider){
                $routeProvider.when("/all_talk",{
                    templateUrl:"all_talk/all_talk.html",
                    controller:"allTalkCtrl"
                })
        }])
        .controller("allTalkCtrl",["$scope","$http","$window","$timeout","formatDate",function($scope,$http,$window,$timeout,formatDate){
            $('[data-toggle="tooltip"]').tooltip();
            $('#myTab a').click(function (e) {
                e.preventDefault();
                $(this).tab('show')
            });
            var username=$window.localStorage.getItem("username");
            $scope.headImgPath="";
            $scope.content="";
            $scope.showInfo=false;
            $scope.subjects=[];
            $scope.obj={};
            $scope.flag1=false;
            $scope.flag2=true;
            $scope.page=1;
            $scope.pageNum=2;
            $scope.updateNum=0;
            $scope.buttonInfo="加载显示更多...";
            $scope.totalPage=0;
            //显示、隐藏全文
            $scope.showAll=function(event){
                $(event.target).parent().siblings().removeClass("ng-hide");
                $(event.target).parent().siblings().find("span").removeClass("ng-hide")
                $(event.target).parent().addClass("ng-hide");
            };
            $scope.hideAll=function(){
                $(event.target).parent().addClass("ng-hide");
                $(event.target).parent().siblings().removeClass("ng-hide");
            };
            //获取用户信息
               $http({
                   url:"/getUserInfo?username="+username,
                   method:"get"
               }).then(function(res){
               $scope.headImgPath="../images/"+res.data.result[0].headImg;
            },function(err){
               console.log(err)
            });
//            alert(formatDate.format(new Date()));
            //发布说说
            $scope.postInfo=function(){
               $http({
                   url:"/postInfo",
                   method:"post",
                   data:{
                       username:username,
                       content:$scope.content,
                       headImg: $scope.headImgPath
                   }
               }).then(function(res){
                    if(res.data.data=="success"){
                         $scope.obj={date:formatDate.format(new Date()),
                            username:username,
                            headImg:$scope.headImgPath,
                            content:$scope.content,
                            comment:[],
                            favours:[]};
                        $scope.subjects.unshift($scope.obj);
                        $scope.showInfo=true;
                        $scope.content="";
                        $scope.updateNum++;
                        $timeout(function(){
                            $scope.showInfo=false
                        },1000)
                    }
               },function(err){
                   console.log(err)
               })
            };
            //获取第一页说说
            $http({
                url:"/getAllTalk",
                method:"post",
                data:{
                    page:$scope.page,
                    pageNum:$scope.pageNum,
                    updateNum:$scope.updateNum
                }
            }).then(function(res){
                for(var i=0;i<res.data.result.length;i++){
                    res.data.result[i].date=formatDate.format(new Date(res.data.result[i].date))
                }
                $scope.subjects=res.data.result;
                $scope.totalPage=Math.ceil(parseInt(res.data.sum)/parseInt($scope.pageNum));
                $scope.page++;
            },function(err){
                console.log(err)
            });
            //加载更多数据
            $scope.loadMore=function(){
                if($scope.page>$scope.totalPage){
                    return;
                }
                $http({
                    url:"/getAllTalk",
                    method:"post",
                    data:{
                        page:$scope.page,
                        pageNum:$scope.pageNum,
                        updateNum:$scope.updateNum
                    }
                }).then(function(res){
                    for(var i=0;i<res.data.result.length;i++) {
                        res.data.result[i].date = formatDate.format(new Date(res.data.result[i].date))
                        $scope.subjects.push(res.data.result[i]);
                    }
                    $scope.page++;
                    if($scope.page>$scope.totalPage){
                        $scope.buttonInfo="没有更多数据...";
                    }
                },function(err){
                    console.log(err)
                });
            }
        }])
})(angular,jQuery);